// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "M2 Ultra",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "M2 Ultra",
            targets: ["AppModule"],
            bundleIdentifier: "com.alwaysboringstudio.m2ultra",
            teamIdentifier: "UGQBX3P3M8",
            displayVersion: "1.0",
            bundleVersion: "2",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .developerTools
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)
